routenplaner/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import reverse, reverse_lazy
from django.conf import settings

from . import views

#######################

app_name = 'routenplaner'
urlpatterns = [
    path('route/<object_id>/', views.view_route, name="view-route"),
    path('route/', views.routes, name="routes"),
    path('manifest.json', views.manifest, name="manifest")
]

routenplaner/models.py
from django.db import models
from django.utils.html import mark_safe
from django.utils.http import urlencode

# Create your models here.


def chunks(lst, n):
    for i in range(0, len(lst), n):
        yield lst[i:i + n]


class Route(models.Model):
    name = models.CharField("Name", max_length=50)

    def get_orte(self):
        return self.orte.filter(aktiv=True).order_by("pos")

    def get_google_maps_routes(self):
        url = "https://www.google.com/maps/dir/"
        urls = []
        for chunk in chunks([ort.adresse for ort in self.orte.all()], 9):
            urls.append(url + "/".join(chunk))
        print(urls)

    def __str__(self):
        return self.name
    __str__.short_description = "Route"

    class Meta:
        verbose_name = "Route"
        verbose_name_plural = "Routen"


class Ort(models.Model):
    pos = models.IntegerField("Position", default=0)
    aktiv = models.BooleanField("Aktiv", default=True)

    name = models.CharField("Name", max_length=50)
    adresse = models.CharField("Adresse", max_length=100)

    route = models.ForeignKey(
        Route, on_delete=models.CASCADE, related_name="orte")

    def get_maps_link(self):
        if self.pk:
            link = "https://maps.apple.com/?"
            args = urlencode(
                {
                    'daddr': self.adresse,
                    'dirflg': 'd'
                }
            )
            return link + args
        else:
            return "-"

    def html_link(self):
        if self.pk:
            html = ('<a href="' + self.get_maps_link() +
                    '" target="_blank">Maps</a>')
            print(html)
            return mark_safe(html)
        else:
            return "-"
    html_link.short_description = "Link"

    def html_adresse(self):
        return mark_safe(self.adresse.replace(",", "<br>"))

    def __str__(self):
        return self.name + " - " + self.adresse
    __str__.short_description = "Ort"

    class Meta:
        verbose_name = "Ort"
        verbose_name_plural = "Orte"

routenplaner/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required, permission_required

from .models import Route

# Create your views here.


@login_required
@permission_required("routenplaner.view_route")
def view_route(request, object_id):
    if Route.objects.filter(id=int(object_id)).exists():
        obj = Route.objects.get(id=int(object_id))
        return render(request, "routenplaner/view-route.html", {
            "route": obj,
            "orte": obj.get_orte(),
        })
    else:
        messages.error(request, "Route konnte nicht gefunden werden!")
        return redirect(reverse("admin:routenplaner_route_changelist"))


@login_required
@permission_required("routenplaner.view_route")
def routes(request):
    return render(request, "routenplaner/routes.html", {
        "routes": Route.objects.all(),
    })


def manifest(request):
    response = render(request, "routenplaner/manifest.json", {})
    response['Content-Type'] = 'text/json'
    response["Service-Worker-Allowed"] = "/"
    return response

routenplaner/templates/routenplaner/routes.html
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="apple-mobile-web-app-status-bar-style" content="black">

        <link rel="manifest" href="{% url 'routenplaner:manifest' %}">

        <title>
            Routenplaner
        </title>

        {% load static %}
        <link rel="stylesheet" href="{% static 'routenplaner/css/routes.css' %}">

        <link rel="shortcut icon" type="image/x-icon" href="{% static "routenplaner/favicon.ico" %}">
        <link rel="apple-touch-icon" href="{% static "routenplaner/favicon.ico" %}">

    </head>
    <body>
        <center>
            <h1>Routenplaner
                {% if user.is_staff %}
                    <a class="link" href="{% url 'admin:routenplaner_route_changelist' %}">
                        <i class="edit">✎</i>
                    </a>
                {% endif %}
            </h1>
            {% for route in routes %}
                <a class="route" href="{% url 'routenplaner:view-route' object_id=route.id %}">
                    <b>{{ route.name }}</b>
                </a>
            {% endfor %}
        </center>
    </body>
</html>

routenplaner/templates/routenplaner/view-route.html
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="apple-mobile-web-app-status-bar-style" content="black">

        <link rel="manifest" href="{% url 'routenplaner:manifest' %}">

        <title>
            {{ route.name }}
            - Routenplaner
        </title>

        {% load static %}
        <link rel="stylesheet" href="{% static 'routenplaner/css/view-route.css' %}">
        <script src="{% static 'routenplaner/js/view-route.js' %}"></script>

    </head>
    <body>
        <div id="sidebar">
            <header>
                <h2 class="disable-select">
                    <a class="link" href="{% url 'routenplaner:routes' %}">
                        <i class="arrow left"></i>
                    </a>
                    Orte ({{ orte.count }})
                    {% if user.is_staff %}
                        <a class="link" href="{% url 'admin:routenplaner_route_change' object_id=route.id %}">
                            <i class="edit">✎</i>
                        </a>
                    {% endif %}
                </h2>
            </header>
            <nav>
                <table id="orte" cellspacing="0">
                    {% for ort in orte %}
                        <tr class="ort" data-url="{{ ort.get_maps_link }}" data-id="{{ ort.pos }}" data-name="{{ ort.name }}" data-address="{{ ort.adresse }}">
                            <td class="id">
                                <u class="id">{{ ort.pos }}</u>
                            </td>
                            <td class="infos">
                                <b>{{ ort.name }}</b>
                                <br>
                                <i>{{ ort.html_adresse }}</i>
                            </td>
                            <td class="button disable-select">
                                <a onclick="route_setLocation(this.parentNode.parentNode);">Go</a>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </nav>
        </div>
        <div id="content">
            <center>
                <h1>{{ route.name }}</h1>
                <div id="locationinfo">
                    <b id="locationid">?</b>
                    <br>
                    <span id="locationname">Laden...</span>
                    <br>
                    <i id="locationaddress">Wird geladen...</i>
                </div>
                <br>
                <br>
                <div id="locationbuttons" class="disable-select">
                    <a class="btn disabled" id="buttonprevious" onclick="route_back();">Zurück</a>
                    <a class="btn" id="locationurl" target="_blank" href="#">Karte</a>
                    <a class="btn disabled" id="buttonnext" onclick="route_next();">Weiter</a>
                </div>
            </center>
        </div>
    </body>
</html>